services:
  face-recognition-system-api-app:
    container_name: face_recognition_system_container
    build: . 
    restart: always
    # command: gunicorn -w 16 App.Main:app --bind 0.0.0.0:8000 --timeout 300
    command: uvicorn App.Main:app --host 0.0.0.0 --port 8000
    env_file:
      - Config/.env
    volumes:
      - ./:/usr/src/app
 


  nginx:
    container_name: nginx_container
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - face-recognition-system-api-app