CREATE DATABASE "AgroAI_API";

\c "AgroAI_API"


CREATE TABLE roles
(
    role_id bigint generated by default as identity,
    role_type character varying not null,

    constraint roles_pkey primary key (role_id)
);

INSERT INTO roles
    (role_id, role_type) 
VALUES 
    (1, 
    'super admin'),

    (2, 
    'admin'),

    (3, 
    'employee') 
;


CREATE TABLE users
(
    user_id uuid not null default gen_random_uuid (),
    email character varying not null,
    first_name character varying not null,
    last_name character varying not null,
    password character varying not null,
    role bigint not null,
    working_status boolean not null,
    created_at timestamp with time zone not null default now(),

    constraint users_pkey1 primary key (email),
    constraint users_user_id_key unique (user_id),
    constraint public_users_role_fkey foreign key (role) references roles (role_id)
);

INSERT INTO users
    (email, first_name, last_name, password, role, working_status) 
VALUES 
    ('lingges@uthm.com.my', 
    'lingges',
    'arulsamy', 
    '730748e79668a7a0f3272ded55ebd80a14b1873b396b8ae43a6e577b1be98c1b',
    1,
    TRUE),
    
    ('rozaida@uthm.com.my', 
    'rozaida',
    'ghazali', 
    '1069caf6551feb160a625f0289817bc35dc31bd4ccc19b40882a45ae7968d487',
    2,
    TRUE),

    ('cheong@uthm.com.my', 
    'cheong',
    'yong', 
    'e6d21bbbb920931cdcc686eb09bb905a1e6c0af9541f4fc31976af3882b2f95b',
    3,
    TRUE)
;



